### ISSUE TITLE
the drawtree installed by pip can not be imported

### ISSUE THREAD

**Issue by hotea** [msbanik/drawtree#6]
environment:
Python 3.6.4
pip 9.0.1

the Exception is:
`ImportError: cannot import name 'draw_bst'
`
which from `lib/python3.6/site-packages/drawtree/__init__.py`

maybe the pypi package not be upgrade, it shows latest uploaded date is 2015-10-03, and version is drawtree 0.1.1

**Comment by ulkaio** [comment]
Sorry for the late response, latest version uploaded to pypi 
https://pypi.python.org/pypi/drawtree

**Comment by msbanik** [comment]
Sorry for the late response, latest version uploaded to pypi 
https://pypi.python.org/pypi/drawtree
